project_id = "lrjhpflvkrebbngfnaif"

[functions.movie-chat]
verify_jwt = false

[functions.movie-match]
verify_jwt = false

[functions.surprise-personalized]
verify_jwt = false

[functions.scribe-token]
verify_jwt = false

[functions.companion-chat]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.cinematic-profile]
verify_jwt = false

[functions.group-recommend]
verify_jwt = false

[functions.join-session]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
